BEGIN TRAN 
   SELECT 1
BEGIN TRAN 
   SELECT 1
COMMIT TRAN

SELECT * FROM sys.sysprocesses WHERE open_tran > 0

--DBCC OPENTRAN

SELECT er.session_id,er.open_transaction_count
FROM sys.dm_exec_requests er


SELECT SP.SPID,[TEXT] as SQLcode FROM SYS.SYSPROCESSES SP
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SP.[SQL_HANDLE])AS DEST WHERE OPEN_TRAN > 0

IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;